# Generated by Django 3.2.3 on 2021-05-25 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_post_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='author',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
